version: '3'
services:
  nginx-ui-no-auth:
    container_name: nginx-ui-no-auth
    build: .
    image: nginx-ui-no-auth:latest
    ports:
      - 9000:9000
    volumes:
      - nginx:/etc/nginx

  nginx:
    container_name: nginx
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
    volumes:
      - nginx:/etc/nginx

volumes:
  nginx:
